; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "HwGDReqs"
#define MyAppVersion "1.11.4"
#define MyAppPublisher "MalikHw47"
#define MyAppURL "https://hwgdreqs.github.io"
#define MyAppExeName "HwGDReqs.exe"

[Setup]
AppId={{08EF5909-2044-469E-BDE3-6DE680460E8E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ArchiveExtraction=full
DisableProgramGroupPage=yes
LicenseFile=LICENSE
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=HwGDReqs-setup-online
SetupIconFile=assets\logo.ico
SolidCompression=yes
WizardSmallImageFile=inno-assets\wizard-small.bmp
WizardImageFile=inno-assets\big.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "https://github.com/HwGDReqs/HwGDReqs/releases/download/1.11.4/hwgdreqs-windows-portable.zip"; DestDir: "{app}"; DestName: "hwgdreqs-windows-portable.zip"; ExternalSize: "66374861"; Flags: external download extractarchive ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function IsUpgrade(): Boolean;
var
  I: Integer;
  P: String;
begin
  Result := False;
  if (Pos('-up', Lowercase(GetCmdTail)) > 0) or (Pos('/up', Lowercase(GetCmdTail)) > 0) then
  begin
    Result := True;
    Exit;
  end;
  for I := 1 to ParamCount do
  begin
    P := Lowercase(ParamStr(I));
    if (P = '-up') or (P = '/up') or (Pos('-up', P) = 1) or (Pos('/up', P) = 1) then
    begin
      Result := True;
      Exit;
    end;
  end;
end;

function GetExistingInstallDir(): String;
var
  InstallDir: String;
begin
  InstallDir := '';
  if Is64BitInstallMode then
  begin
    if not RegQueryStringValue(HKCU64, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'Inno Setup: App Path', InstallDir) then
    begin
      if not RegQueryStringValue(HKLM64, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'Inno Setup: App Path', InstallDir) then
      begin
        if not RegQueryStringValue(HKCU64, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'InstallLocation', InstallDir) then
        begin
          RegQueryStringValue(HKLM64, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'InstallLocation', InstallDir);
        end;
      end;
    end;
  end;

  if InstallDir = '' then
  begin
    if not RegQueryStringValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'Inno Setup: App Path', InstallDir) then
    begin
      if not RegQueryStringValue(HKLM, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'Inno Setup: App Path', InstallDir) then
      begin
        if not RegQueryStringValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'InstallLocation', InstallDir) then
        begin
          RegQueryStringValue(HKLM, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{08EF5909-2044-469E-BDE3-6DE680460E8E}_is1', 'InstallLocation', InstallDir);
        end;
      end;
    end;
  end;
  Result := InstallDir;
end;

procedure InitializeWizard();
var
  PrevDir: String;
begin
  if IsUpgrade() then
  begin
    PrevDir := GetExistingInstallDir();
    if PrevDir <> '' then
    begin
      WizardForm.DirEdit.Text := PrevDir;
    end;
  end;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if IsUpgrade() then
  begin
    case PageID of
      wpWelcome,
      wpLicense,
      wpPassword,
      wpInfoBefore,
      wpUserInfo,
      wpSelectDir,
      wpSelectComponents,
      wpSelectProgramGroup,
      wpSelectTasks,
      wpReady:
        Result := True;
    end;
  end;
end;