; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "HwGDReqs"
#define MyAppVersion "0.17.1"
#define MyAppPublisher "MalikHw47"
#define MyAppURL "https://hwgdreqs.github.io"
#define MyAppExeName "HwGDReqs.exe"

[Setup]
AppId={{08EF5909-2044-469E-BDE3-6DE680460E8E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ArchiveExtraction=full
DisableProgramGroupPage=yes
LicenseFile=LICENSE
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=HwGDReqs-setup-online
SetupIconFile=assets\logo.ico
SolidCompression=yes
WizardSmallImageFile=inno-assets\wizard-small.bmp
WizardImageFile=inno-assets\big.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "https://github.com/HwGDReqs/HwGDReqs/releases/download/0.17.1/hwgdreqs-windows-portable.zip"; DestDir: "{app}"; DestName: "hwgdreqs-windows-portable.zip"; ExternalSize: "66374861"; Flags: external download extractarchive ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent