name: AUR

on:
  workflow_dispatch:

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate SHA256
        run: |
          VERSION=$(grep -Po 'pkgver=\K[^\n]+' PKGBUILD)
          SHA256=$(curl -L "https://github.com/${{ github.repository }}/archive/v$VERSION.tar.gz" | sha256sum | cut -d' ' -f1)
          sed -i "s/sha256sums=('.*')/sha256sums=('$SHA256')/g" PKGBUILD
          sed -i "s/sha256sums = .*/sha256sums = $SHA256/g" .SRCINFO
      
      - name: Push to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: hwgdreqs
          pkgbuild: ./PKGBUILD
          srcinfo: ./.SRCINFO
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update PKGBUILD"