name: AUR

on:
  workflow_dispatch:

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate SHA256
        run: |
          VERSION=$(grep -Po 'pkgver=\K[^\n]+' PKGBUILD)
          SHA256=$(curl -L "https://github.com/${{ github.repository }}/archive/v$VERSION.tar.gz" | sha256sum | cut -d' ' -f1)
          sed -i "s/sha256sums=('.*')/sha256sums=('$SHA256')/g" PKGBUILD
          sed -i "s/sha256sums = .*/sha256sums = $SHA256/g" .SRCINFO
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
      
      - name: Push to AUR
        run: |
          git clone ssh://aur@aur.archlinux.org/hwgdreqs.git aur-repo
          
          cp PKGBUILD aur-repo/
          cp .SRCINFO aur-repo/
          
          cd aur-repo
          git config user.name "${{ secrets.AUR_USERNAME }}"
          git config user.email "${{ secrets.AUR_EMAIL }}"
          git add PKGBUILD .SRCINFO
          git commit -m "Update PKGBUILD"
          git push