name: Windows Build and Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'release tag'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: pyinst.bat
      shell: cmd
      run: |
        python -m pip install pyinstaller
        python -m pip install -r requirements.txt
        python -m PyInstaller HwGDReqs.spec
    
    - name: dist/hwgdreqs zip
      shell: pwsh
      run: |
        Compress-Archive -Path dist/hwgdreqs/* -DestinationPath hwgdreqs-windows-portable.zip -Force
    
    - name: upload asset to release
      shell: pwsh
      run: |
        Write-Host "Uploading to release: ${{ github.event.inputs.release_tag }}"
        gh release upload "${{ github.event.inputs.release_tag }}" hwgdreqs-windows-portable.zip --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hwgdreqs-windows-portable
        path: hwgdreqs-windows-portable.zip